In [63]:
from splinter import Browser
from bs4 import BeautifulSoup
import pandas as pd
import time
import numpy as np


import requests
import pymongo

# SQL Alchemy
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float
Base = declarative_base()

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Set path 
import sys


# Config variables
from config import local_gwsis_dbname, local_gwsis_dbuser, local_gwsis_dbpwd
from config import remote_db_endpoint, remote_db_port
from config import remote_gwsis_dbname, remote_gwsis_dbuser, remote_gwsis_dbpwd

# Import Pandas
import pandas as pd

import datetime
from time import gmtime, strftime, strptime
from datetime import timedelta
import requests
import json
import statsmodels.api as sm
from scipy import stats
from sklearn import datasets, linear_model

In [41]:
aengine = create_engine(f"mysql://{remote_gwsis_dbuser}:{remote_gwsis_dbpwd}@{remote_db_endpoint}:{remote_db_port}/{remote_gwsis_dbname}")
aconn = aengine.connect()
aengine

Engine(mysql://root:***@codingbootcamp.ctxjv3tnsa2p.us-east-2.rds.amazonaws.com:3306/gwsis)

In [16]:
master_15_day = pd.read_sql('SELECT * FROM master_15_day',aconn)
master_30_day = pd.read_sql('SELECT * FROM master_30_day',aconn)
master_45_day = pd.read_sql('SELECT * FROM master_45_day',aconn)
master_60_day = pd.read_sql('SELECT * FROM master_60_day',aconn)

In [29]:

correlation_30 = master_30_day.drop(['index','Stock Name','Reported Date','30 Days'],axis=1)
correlation_30.loc[correlation_30['30 Days Later Stock Price'] == 'N/A','30 Days Later Stock Price'] = np.nan
correlation_30 = correlation_30.dropna()

In [30]:
for x in correlation_30.columns:
    correlation_30[x] = pd.to_numeric(correlation_30[x])

In [77]:
correlation_30.corr()

Earnings Date Stock Price  \
Earnings Date Stock Price                       1.000000   
30 Days Later Stock Price                       0.996611   
Chaikin A/D line                                0.049025   
ADX                                            -0.011121   
Aroon Up                                        0.033882   
Aroon Down                                     -0.052323   
Lower Band                                      0.997825   
Middle Band                                     0.998260   
Upper Band                                      0.997470   
Lower Band (5)                                  0.998980   
Middle Band (5)                                 0.999299   
Upper Band (5)                                  0.998932   
CCI                                             0.040725   
Earnings Per Share                              0.747473   
Forecasted Earnings Per Share                   0.706390   
% Surprise                                      0.076320   
EMA (20 Day)                                    0.998443   
MACD_Hist                                       0.160987   
MACD_Signal                                     0.190816   
MACD                                            0.221527   
OBV                                             0.024169   
RSI                                             0.056522   
20 Day Moving Average                           0.998260   
5 Day Moving Average                            0.999299   
SlowD                                           0.030215   
SlowK                                           0.024116   
Difference                                     -0.035989   

                               30 Days Later Stock Price  Chaikin A/D line  \
Earnings Date Stock Price                       0.996611          0.049025   
30 Days Later Stock Price                       1.000000          0.049195   
Chaikin A/D line                                0.049195          1.000000   
ADX                                            -0.013408          0.006278   
Aroon Up                                        0.035121          0.011029   
Aroon Down                                     -0.056044         -0.036935   
Lower Band                                      0.994192          0.048137   
Middle Band                                     0.994297          0.048296   
Upper Band                                      0.993216          0.048382   
Lower Band (5)                                  0.996014          0.048092   
Middle Band (5)                                 0.996272          0.047989   
Upper Band (5)                                  0.995849          0.047860   
CCI                                             0.041979          0.018035   
Earnings Per Share                              0.749424          0.008391   
Forecasted Earnings Per Share                   0.709449          0.002777   
% Surprise                                      0.078684          0.069323   
EMA (20 Day)                                    0.994771          0.048235   
MACD_Hist                                       0.177016          0.001186   
MACD_Signal                                     0.202155          0.012908   
MACD                                            0.236645          0.012053   
OBV                                             0.021790         -0.358424   
RSI                                             0.057288          0.029038   
20 Day Moving Average                           0.994297          0.048296   
5 Day Moving Average                            0.996272          0.047989   
SlowD                                           0.032817          0.028112   
SlowK                                           0.024788          0.052826   
Difference                                      0.016206         -0.003328   

                                    ADX  Aroon Up  Aroon Down  Lower Band  \
Earnings Date Stock Price     -0.011121  0.033882   -0.052323    0.997825   
30 Days Lat

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [84]:
X = correlation_30[['Earnings Date Stock Price','20 Day Moving Average','5 Day Moving Average',
                  '% Surprise']]
y = correlation_30['30 Days Later Stock Price']



Earnings Date Stock Price    164.860
20 Day Moving Average        173.075
5 Day Moving Average         168.578
% Surprise                     1.030
Name: 10, dtype: float64

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.4)
model = LinearRegression()

In [93]:
model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)
testing_score

0.991168858119003

In [94]:
model.coef_

array([ 0.91810515, -0.47138262,  0.53376096,  0.01115294])

In [45]:
correlation_30['Difference'] = ((correlation_30['30 Days Later Stock Price'] - correlation_30['Earnings Date Stock Price'])/correlation_30['Earnings Date Stock Price'])*100

In [58]:
x = [[78.59,84.4825,82.608,11.31]]

In [96]:
model.predict([X.iloc[1,:]])

array([67.05425484])

In [79]:
master_30_day

index Stock Name Reported Date     30 Days Earnings Date Stock Price  \
0         0        AOS    04/25/2018  05/25/2018                      61.5   
1         1        ABT    07/18/2018  08/17/2018                     64.75   
2         2       ABBV    04/26/2018  05/24/2018                     97.44   
3         3       ABMD    05/03/2018  05/31/2018                    335.57   
4         4        ACN    06/28/2018  07/26/2018                     164.5   
5         5       ATVI    05/03/2018  05/31/2018                     66.82   
6         6       ADBE    06/14/2018  07/12/2018                     258.1   
7         7        AAP    05/22/2018  06/21/2018                    115.33   
8         8        AMD    04/25/2018  05/25/2018                      9.71   
9         9        AES    05/08/2018  06/07/2018                     11.73   
10       10        AMG    04/30/2018  05/30/2018                    164.86   
11       11        AFL    04/25/2018  05/25/2018                     45.41   
12       12          A    05/14/2018  06/13/2018                     69.21   
13       13        APD    07/26/2018  08/23/2018                    161.55   
14       14       AKAM    04/30/2018  05/30/2018                     71.65   
15       15        ALK    04/23/2018  05/23/2018                     69.11   
16       16        ALB    05/09/2018  06/08/2018                    101.75   
17       17        ARE    04/30/2018  05/30/2018                    124.57   
18       18       ALXN    04/26/2018  05/24/2018                    121.42   
19       19       ALGN    07/25/2018  08/24/2018                    381.77   
20       20       ALLE    04/26/2018  05/24/2018                     78.59   
21       21        AGN    04/30/2018  05/30/2018                    153.65   
22       22        ADS    04/19/2018  05/17/2018                    211.66   
23       23        LNT    05/02/2018  06/01/2018                     42.87   
24       24        ALL    05/01/2018  05/31/2018                      98.2   
25       25         MO    04/26/2018  05/24/2018                     54.77   
26       26        AEE    05/09/2018  06/08/2018                     56.22   
27       27        AAL    04/26/2018  05/24/2018                     42.37   
28       28        AEP    04/26/2018  05/24/2018                     69.77   
29       29        AIG    05/02/2018  06/01/2018                     54.84   
...     ...        ...           ...         ...                       ...   
1858   1863       ZION    04/22/2019  05/24/2019                     46.71   
1859   1864        UNP    04/18/2019  05/20/2019                    176.66   
1860   1865        UAL    04/16/2019  05/18/2019                     85.17   
1861   1866        UPS    04/25/2019  05/27/2019                    105.13   
1862   1867        URI    04/17/2019  05/19/2019                    125.76   
1863   1868        UHS    04/25/2019  05/27/2019                     131.7   
1864   1869        UNM    02/05/2019  03/07/2019                     34.69   
1865   1870        VFC    01/18/2019  02/15/2019                     82.34   
1866   1871        VLO    04/25/2019  05/27/2019                     90.83   
1867   1872        VAR    04/24/2019  05/26/2019                    133.27   
1868   1873        VTR    02/08/2019  03/08/2019                     64.27   
1869   1874       VRSN    04/25/2019  05/27/2019                    189.18   
1870   1875       VRSK    02/19/2019  03/21/2019                    124.43   
1871   1876       VRTX    02/05/2019  03/07/2019                    187.02   
1872   1877       VIAB    02/05/2019  03/07/2019                     30.33   
1873   1878        VNO    02/11/2019  03/13/2019                     70.07   
1874   1879        VMC    02/14/2019  03/14/2019                    112.69   
1875   1880        WAB    04/25/2019  05/27/2019                     71.46   
1876   1881         WM    04/25/2019  05/27/2019                    105.52   
1877   1882        WAT    04

In [67]:
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                                OLS Regression Results                               
Dep. Variable:     30 Days Later Stock Price   R-squared:                       0.994
Model:                                   OLS   Adj. R-squared:                  0.994
Method:                        Least Squares   F-statistic:                 7.234e+04
Date:                       Thu, 02 May 2019   Prob (F-statistic):               0.00
Time:                               19:07:22   Log-Likelihood:                -6684.4
No. Observations:                       1722   AIC:                         1.338e+04
Df Residuals:                           1717   BIC:                         1.341e+04
Df Model:                                  4                                         
Covariance Type:                   nonrobust                                         
                                coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------

In [68]:
clf  = linear_model.Lasso(alpha=.05)
clf.fit(X,y)

C:\Users\Owner\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


Lasso(alpha=0.05, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [73]:

clf.score(X_test, y_test)

0.9946622626908319

In [70]:
model.coef_

array([ 0.63967528, -0.74229618,  1.08109026,  0.00957099])